### ISSUE TITLE
[DFL:Router] Failed to init internal navigators, trying again / Trying to init internal navigator again

### ISSUE THREAD

**Issue by eXhumer** [SteamDeckHomebrew/decky-frontend-lib#101]
I was trying to access some window variable to use in a plugin when I encountered a never ending warning/error spam in the SharedJSContext due to failed initialization of internal navigators.

https://github.com/SteamDeckHomebrew/decky-frontend-lib/blob/4d4cfedfe09c5c9278179a281c96c8bbbcc1c917/src/deck-components/Router.tsx#L149-L153

Video showing issue while trying to access CEF from remote debugging.

https://github.com/SteamDeckHomebrew/decky-frontend-lib/assets/62310242/dc492b94-5e0f-42df-8af3-deb5fc89c77d

I am on the preview channel of SteamOS and currently have 3.5.13 installed. I rebuilt the latest pre-release version of decky-loader with DFL 3.24.4 (which includes a timeout increase from 100ms to 2000ms). This significantly reduced the amount of warning/error I received, but the internal navigators initialization problem still exists.

**Comment by eXhumer** [comment]
No, I have logged in and am at the main menu.

**Comment by GedasFX** [comment]
I got a bug report (https://github.com/GedasFX/decky-cloud-save/issues/56) having tested 2 versions of my plugin with different frontend versions, and it appears that router in ^3.23.0 does not work, but interestingly, in ^3.21.5 it works just fine. Maybe this is related?

**Comment by AAGaming00** [comment]
You need to use 3.24.2 or higher for functional navigator. Please reopen if this does not solve your issue.

**Comment by eXhumer** [comment]
```json
  "dependencies": {
    "decky-frontend-lib": "^3.24.4",
    "react-icons": "^5.0.1"
  },
```

**Comment by eXhumer** [comment]
So, I guess this is simply means all plugins with updated DFL will now ship with a broken Router from future SteamOS releases. If you want to test this yourself, simply build the decky-plugin-template with latest DFL and try to navigate to the library with the given template plugin...

I don't have the option to reopen this issue...

**Comment by AAGaming00** [comment]
You're supposed to use the `Navigation` API to *navigate*, there really shouldn't be any navigation-related stuff directly on Router and we should remove those from the typings.

**Comment by AAGaming00** [comment]
The real issue here is the template (and loader) using the wrong APIs for this, I can fix this later.

**Comment by GedasFX** [comment]
I was using `Navigation` to navigate. ^3.21.5 worked, ^3.23.0 did not, and latest ^3.24.4 worked again.
