### ISSUE TITLE
Usage of colors in text

### ISSUE THREAD

**Issue by sasdallas** [SteamDeckHomebrew/decky-frontend-lib#33]
Is it possible to add colors onto text? I'm talking about headers, names, descriptions, etc.
Usage of such a feature could vary from defining the colors in-text or just by using a sort of `setColor` method.

Thank you!

**Comment by sasdallas** [comment]
I want to make it clear so that if this already exists, I did not know about it and will close my post happily.

**Comment by TrainDoctor** [comment]
You can do this in base HTML/JS.
