### ISSUE TITLE
Modals not working, showing blurred errors

### ISSUE THREAD

**Issue by Xarishark** [SteamDeckHomebrew/decky-frontend-lib#68]
**Description**
Got my steamdeck today and installed deck os 3.4(preview) when I installed decky loader and tried for example the guide plugin it failed to load a page and the overlay was stuck. I restarted the deck and tried the boot animation plugin but after sellecting a video the same thing happened. all I get is a blurred error(as its behind some kind of effect the decky produces for lower graphical layers and its even impossible to press the password to go to desktop mode and restart. 

 - SteamOS Version: ``3.4 or 20221202.101``
 - Selected Update Channel:Preview

**Comment by FrogTheFrog** [comment]
@AAGaming00 This issue can be closed now, no?
