### ISSUE TITLE
Missing exports

### ISSUE THREAD

**Issue by geeksville** [SteamDeckHomebrew/decky-frontend-lib#77]
Hi ya'll,

A question about 'supported' exports from the DFL:

Is there a way to get the steam ID # for the current user?   Or a way to get the AppOverview for a given appId?  Currently I had to add the following defs to my project:

```
// FIXME - find a better source for these defs?, I'm hand specifying here
// based on looking at ProtonDB plugin
declare let App: any // used for m_currentUser

declare namespace appStore {
  function GetAppOverviewByGameID(appId: number): AppOverview
}
```

But I'd like to remove these.  Do you want me to send in a PR to export these?  I haven't written JS/TS code in a **long** time so I might just be doing something dumb and you are already exporting them?

**Comment by doZennn** [comment]
I typed some of those a while back: https://github.com/SteamDeckHomebrew/decky-frontend-lib/blob/main/src/deck-components/index.ts#L41
