### ISSUE TITLE
wrapReactType called on the same element causes ui to crash

### ISSUE THREAD

**Issue by Tormak9970** [SteamDeckHomebrew/decky-frontend-lib#87]
having two plugins call wrapReactType on the same element causes the ui to crash

**Comment by Tormak9970** [comment]
see: [https://github.com/SteamDeckHomebrew/decky-frontend-lib/pull/88](https://github.com/SteamDeckHomebrew/decky-frontend-lib/pull/88)

**Comment by TrainDoctor** [comment]
Fixed w/ merge of #88.
